version: '3.3'

services:
    modsec3-nginx:
        container_name: modsec3-nginx
        image: owasp/modsecurity-crs:nginx
        environment:
            SERVERNAME: modsec3-nginx
            BACKEND: http://honeypots
            PORT: "80"
            MODSEC_RULE_ENGINE: DetectionOnly
            BLOCKING_PARANOIA: 4
            ERRORLOG: "/var/log/nginx/error.log"
            LOGLEVEL: "info"
            ACCESSLOG: "/var/log/nginx/access.log"
            MODSEC_AUDIT_LOG_FORMAT: JSON
            MODSEC_AUDIT_LOG_TYPE: Serial
            MODSEC_AUDIT_LOG: "/var/log/nginx/modsec_audit.log"
            MODSEC_RESP_BODY_ACCESS: "On"
            MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
            MAX_FILE_SIZE: "64100"
            COMBINED_FILE_SIZES: "65535"
            CRS_ENABLE_TEST_MARKER: 1
            VALIDATE_UTF8_ENCODING: 1
        volumes:
            - ./logs/modsec3-nginx:/var/log/nginx:rw
            - ./rules:/opt/owasp-crs/rules:ro
            - ./plugins:/opt/owasp-crs/plugins:ro
            - ./crs-setup.conf.example:/etc/modsecurity.d/owasp-crs/crs-setup.conf.example
        entrypoint: ["/bin/sh", "-c"]
        command: >
            "
            /bin/cp /etc/modsecurity.d/owasp-crs/crs-setup.conf.example /etc/modsecurity.d/owasp-crs/crs-setup.conf && 
            /docker-entrypoint.sh nginx -g 'daemon off;'
            "
        ports:
        - 80:80         # HTTP
        - 443:443       # HTTPS
        
    honeypots:
        image: justsky/honeypots
        container_name: honeypots
        tty: true
        entrypoint: ["bash", "-c"]
        command: >
            "
            python3 -m honeypots --config config.json --setup all 
            "
        expose:
            - 80
            - 443
        volumes:
            - ./honeypot_logs:/honeypots/logs
            - ./honeypot_config.json:/honeypots/config.json
